server:
  # 运行端口
  port: 9528

jwt:
  token-header: Authorization
  token-start-with: Bearer

spring:
  application:
    name: irisz-blog-backend
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://xxxxxxx.cn:3306/irisz_blog?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    # 数据库用户名&密码
    username: xxxxxx
    password: xxxxxx

    # 数据库连接池配置
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 500000
  redis:
    host: xxxxxx
    port: 6379
    database: 1

mybatis-plus:
  # mapper xml映射目录
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Actuator Web 访问端口
management:
  server:
    # 应用服务 WEB 访问端口
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
